<span style="font-size:1.2em;font-weight:bold">Weighting-MCDM LOPCOW (Logarithmic Percentage Change-Driven Objective Weighting) METHOD</span>

<span style="font-size:1em">
A company is looking to select a new software development project from four options: Project A, Project B, Project C, and Project D. The decision criteria are:
</br>
1. Budget</br>
2. Duration</br>
3. Team Experience</br>
4. Risk Level</br>
</br>
Steps:</br>
1-Normalizing the data..</br>
2-Calculating the logarithmic percentage changes..</br>
3-Calculating the weights using LOPCOW..</br>
</span>

In [1]:
import numpy as np

# Criteria data for each project
data = np.array([
    [200000, 12, 5, 3],  # Project A
    [150000, 10, 7, 2],  # Project B
    [250000, 15, 6, 4],  # Project C
    [180000, 9, 4, 3]    # Project D
])

# Adım 1: Verileri normalize etme / Step 1: Normalizing the data
def normalize(data):
    # Normalize the data (Min-Max normalization)
    normalized_data = (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))
    return normalized_data

normalized_data = normalize(data)

# Adım 2: Logaritmik yüzde değişimlerini hesaplama / Step 2: Calculating the logarithmic percentage changes
def log_percentage_change(normalized_data):
    log_change = np.log1p(normalized_data) - np.log1p(np.mean(normalized_data, axis=0))
    return log_change

log_change = log_percentage_change(normalized_data)

# Adım 3: LOPCOW yöntemi ile ağırlıkları hesaplama / Step 3: Calculating the weights using LOPCOW
def calculate_weights(log_change):
    # Calculating the standard deviation for each criterion
    std_dev = np.std(log_change, axis=0)
    # Weights are inversely proportional to the standard deviation
    weights = 1 / std_dev
    # Normalizing the weights
    weights /= weights.sum()
    return weights

weights = calculate_weights(log_change)

# Sonuçları yazdırma / Printing the results
print("Normalized Data (Normalize Edilmiş Veriler):\n", normalized_data)
print("\nLogarithmic Percentage Changes (Logaritmik Yüzde Değişimleri):\n", log_change)
print("\nWeights (Ağırlıklar):\n", weights)


Normalized Data (Normalize Edilmiş Veriler):
 [[0.5        0.5        0.33333333 0.5       ]
 [0.         0.16666667 1.         0.        ]
 [1.         1.         0.66666667 1.        ]
 [0.3        0.         0.         0.5       ]]

Logarithmic Percentage Changes (Logaritmik Yüzde Değişimleri):
 [[ 0.03390155  0.05715841 -0.11778304  0.        ]
 [-0.37156356 -0.19415601  0.28768207 -0.40546511]
 [ 0.32158362  0.34484049  0.10536052  0.28768207]
 [-0.10919929 -0.34830669 -0.40546511  0.        ]]

Weights (Ağırlıklar):
 [0.25420611 0.24212348 0.2458747  0.25779572]
