<span style="font-size:1.2em;font-weight:bold">Weighting-MCDM SWARA (Stepwise Weight Assessment Ratio Analysis) METHOD</span>

<span style="font-size:1em">
A person is looking to select a laptop from four options: Laptop A, Laptop B, Laptop C, and Laptop D. The decision criteria are:
</br>
1. Price</br>
2. Performance</br>
3. Battery Life</br>
4. Weight</br>
</br>
Steps:</br>
1-Normalizing the data..</br>
2-Ranking the criteria based on importance..</br>
3-Calculating the comparative importance coefficients..</br>
4-Calculating the weights using SWARA method..</br>
</span>

In [1]:
import numpy as np

# Criteria data for each laptop
data = np.array([
    [1000, 8, 10, 1.5],  # Laptop A
    [1200, 9, 8, 1.7],   # Laptop B
    [900, 7, 9, 1.6],    # Laptop C
    [1100, 8, 7, 1.4]    # Laptop D
])

# Adım 1: Verileri normalize etme / Step 1: Normalizing the data
def normalize(data):
    # Normalize the data (Min-Max normalization)
    normalized_data = (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))
    return normalized_data

normalized_data = normalize(data)

# Adım 2: Kriterleri önem sırasına göre sıralama / Step 2: Ranking the criteria based on importance
# Here, we assume a given ranking: Price > Performance > Battery Life > Weight
rankings = [1, 2, 3, 4]

# Adım 3: Karşılaştırmalı önem katsayılarını hesaplama / Step 3: Calculating the comparative importance coefficients
def calculate_s(rankings):
    # Given the importance sequence
    s = [1.0]  # The first element's s is always 1
    for i in range(1, len(rankings)):
        s.append(float(input(f"Enter the comparative importance coefficient for criterion {i+1} (w.r.t. the previous criterion): ")))
    return np.array(s)

s = calculate_s(rankings)

# Adım 4: SWARA yöntemi ile ağırlıkları hesaplama / Step 4: Calculating the weights using SWARA method
def calculate_weights_swara(s):
    k = np.zeros(len(s))
    q = np.zeros(len(s))
    weights = np.zeros(len(s))
    
    k[0] = 1
    for i in range(1, len(s)):
        k[i] = s[i] + 1
        
    q[0] = 1
    for i in range(1, len(s)):
        q[i] = q[i-1] / k[i]
        
    weights = q / np.sum(q)
    return weights

weights = calculate_weights_swara(s)

# Sonuçları yazdırma / Printing the results
print("Normalized Data (Normalize Edilmiş Veriler):\n", normalized_data)
print("\nComparative Importance Coefficients (Karşılaştırmalı Önem Katsayıları):\n", s)
print("\n")

# Ağırlıkları belirli kriterlerle yazdırma / Printing the weights with specific criteria
criteria = ["Price (Fiyat)", "Performance (Performans)", "Battery Life (Batarya Ömrü)", "Weight (Ağırlık)"]
for i, weight in enumerate(weights):
    print(f"{criteria[i]} Ağırlığı: {weight:.4f}")


Enter the comparative importance coefficient for criterion 2 (w.r.t. the previous criterion):  0.34
Enter the comparative importance coefficient for criterion 3 (w.r.t. the previous criterion):  0.27
Enter the comparative importance coefficient for criterion 4 (w.r.t. the previous criterion):  0.19


Normalized Data (Normalize Edilmiş Veriler):
 [[0.33333333 0.5        1.         0.33333333]
 [1.         1.         0.33333333 1.        ]
 [0.         0.         0.66666667 0.66666667]
 [0.66666667 0.5        0.         0.        ]]

Comparative Importance Coefficients (Karşılaştırmalı Önem Katsayıları):
 [1.   0.34 0.27 0.19]


Price (Fiyat) Ağırlığı: 0.3536
Performance (Performans) Ağırlığı: 0.2639
Battery Life (Batarya Ömrü) Ağırlığı: 0.2078
Weight (Ağırlık) Ağırlığı: 0.1746
